---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sadik.
--- DateTime: 3/23/2025 7:25 PM
---

host_block = "Soil Block"
local stateCycleForSeeding = StateCycle.ready("Soil Block", "_Dug up soil", "_Seeded soil")
local stateCycleForGrowth = StateCycle.ready("_Seeded soil", "_Seeded soil young", "_Seeded soil full")

local timerForGrowth

local seeded = false

function isSeeded()
    return stateCycleForSeeding.getCurrent() == "_Seeded soil"
end

function isGrown()
    return stateCycleForGrowth.getCurrent() == "_Seeded soil full"
end

function handleSound()
    local imageName = getImageName()
    if imageName == "_Dug up soil" then
        playSound("Dig dirt")
    elseif imageName == "_Seeded soil" then
        playSound("Seed pour")
    end
end

function scriptLoaded()
    local growthTime = 12

    if isBlockNearby("Water", 1) then
        growthTime = 7.5
    end

    timerForGrowth = Timer.ready(growthTime, function()
        stateCycleForGrowth.cycle()
        setImageName(stateCycleForGrowth.getCurrent())
    end)

    stateCycleForSeeding.setLoop(false)
    stateCycleForGrowth.setLoop(false)
end

function interacted()
    if isSeeded() and not isGrown() then
        seeded = true
        return
    end

    if isGrown() then
        stateCycleForGrowth.reset()
    end

    stateCycleForSeeding.cycle();
    setImageName(stateCycleForSeeding.getCurrent())

    handleSound()

    if isSeeded() then
        seeded = true
    end
end

function update()
    if seeded then

        timerForGrowth.update()
    end
end
