---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sadik.
--- DateTime: 3/8/2025 9:46 PM
---


host_block = "Soil Block"
local cycle = StateCycle.ready("Soil Block", "Grass Block", "Stone Bricks")

local timer = Timer.ready(3.0, function()
    cycle.cycle()
end)


function update()
    if getImageName() ~= cycle.getCurrent() then
        setImageName(cycle.getCurrent())
    end
    timer.update()
end
